"""Initial migration

Revision ID: a5385ee3247d
Revises: 
Create Date: 2026-03-01 13:07:18.003811

"""
from typing import Optional, Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5385ee3247d'
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('event_details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_table('compliance_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('required_document_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rule_client_type'), 'compliance_rule', ['client_type'], unique=False)
    op.create_index(op.f('ix_compliance_rule_id'), 'compliance_rule', ['id'], unique=False)
    op.create_table('document_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('regex_pattern', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tag_id'), 'document_tag', ['id'], unique=False)
    op.create_index(op.f('ix_document_tag_name'), 'document_tag', ['name'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_queue_id'), 'task_queue', ['id'], unique=False)
    op.create_index(op.f('ix_task_queue_status'), 'task_queue', ['status'], unique=False)
    op.create_index(op.f('ix_task_queue_task_type'), 'task_queue', ['task_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ca_media_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ca_type_order', 'ca_media_item', ['ca_id', 'item_type', 'order_index'], unique=False)
    op.create_index(op.f('ix_ca_media_item_ca_id'), 'ca_media_item', ['ca_id'], unique=False)
    op.create_index(op.f('ix_ca_media_item_id'), 'ca_media_item', ['id'], unique=False)
    op.create_table('ca_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('logo_file_path', sa.String(length=255), nullable=True),
    sa.Column('professional_bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gstin_pan', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ca_id')
    )
    op.create_index(op.f('ix_ca_profile_id'), 'ca_profile', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_tagged', sa.Boolean(), nullable=False),
    sa.Column('tag_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_phone'], ['clients.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_year_filename', 'documents', ['client_phone', 'year', 'file_name'], unique=True)
    op.create_index(op.f('ix_documents_client_phone'), 'documents', ['client_phone'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=False),
    sa.Column('download_type', sa.String(length=20), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('download_token', sa.String(length=255), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_phone'], ['clients.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('download_token')
    )
    op.create_index(op.f('ix_downloads_client_phone'), 'downloads', ['client_phone'], unique=False)
    op.create_index(op.f('ix_downloads_downloaded_at'), 'downloads', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_phone'], ['clients.phone_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_client_phone'), 'messages', ['client_phone'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('compliance_rule_id', sa.Integer(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_ca_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_phone'], ['clients.phone_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_rule_id'], ['compliance_rule.id'], ),
    sa.ForeignKeyConstraint(['created_by_ca_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['document_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_reminder_date', 'reminder', ['client_phone', 'reminder_date'], unique=False)
    op.create_index(op.f('ix_reminder_client_phone'), 'reminder', ['client_phone'], unique=False)
    op.create_index(op.f('ix_reminder_id'), 'reminder', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_reminder_date'), 'reminder', ['reminder_date'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image_path', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_ca_id'), 'service', ['ca_id'], unique=False)
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_table('shared_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_phone', sa.String(length=15), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_phone'], ['clients.phone_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_files_client_phone'), 'shared_files', ['client_phone'], unique=False)
    op.create_index(op.f('ix_shared_files_id'), 'shared_files', ['id'], unique=False)
    op.create_index(op.f('ix_shared_files_sent_at'), 'shared_files', ['sent_at'], unique=False)
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('verified_client_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonial_ca_id'), 'testimonial', ['ca_id'], unique=False)
    op.create_index(op.f('ix_testimonial_id'), 'testimonial', ['id'], unique=False)
    op.create_table('document_document_tag',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['document_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_document_tag')
    op.drop_index(op.f('ix_testimonial_id'), table_name='testimonial')
    op.drop_index(op.f('ix_testimonial_ca_id'), table_name='testimonial')
    op.drop_table('testimonial')
    op.drop_index(op.f('ix_shared_files_sent_at'), table_name='shared_files')
    op.drop_index(op.f('ix_shared_files_id'), table_name='shared_files')
    op.drop_index(op.f('ix_shared_files_client_phone'), table_name='shared_files')
    op.drop_table('shared_files')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_index(op.f('ix_service_ca_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_reminder_reminder_date'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_client_phone'), table_name='reminder')
    op.drop_index('idx_client_reminder_date', table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_client_phone'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_downloaded_at'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_client_phone'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_phone'), table_name='documents')
    op.drop_index('idx_client_year_filename', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ca_profile_id'), table_name='ca_profile')
    op.drop_table('ca_profile')
    op.drop_index(op.f('ix_ca_media_item_id'), table_name='ca_media_item')
    op.drop_index(op.f('ix_ca_media_item_ca_id'), table_name='ca_media_item')
    op.drop_index('idx_ca_type_order', table_name='ca_media_item')
    op.drop_table('ca_media_item')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_queue_task_type'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_status'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_id'), table_name='task_queue')
    op.drop_table('task_queue')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_document_tag_name'), table_name='document_tag')
    op.drop_index(op.f('ix_document_tag_id'), table_name='document_tag')
    op.drop_table('document_tag')
    op.drop_index(op.f('ix_compliance_rule_id'), table_name='compliance_rule')
    op.drop_index(op.f('ix_compliance_rule_client_type'), table_name='compliance_rule')
    op.drop_table('compliance_rule')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
