"""Add slug and display_name to User model

Revision ID: bf8a455fc811
Revises: a5385ee3247d
Create Date: 2026-03-01 14:38:17.865722

"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8a455fc811'
down_revision: Optional[str] = 'a5385ee3247d'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('slug', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_column('users', 'slug')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
